### PR TITLE
Download improvements

### PR DESCRIPTION
**Pull request by ACertainCoder**
This pull request improves the download experience for the user by a lot.

Changes include the following:
- Resumable downloads
- Download size info
- More detailed download dialog
- Better error handling (auto retry in certain scenarios)

Demo video showing the download and install of the German patch for "Jackbox Party Starter":

https://github.com/user-attachments/assets/8db632c8-157f-465b-8a7f-925039fbe138

I've did a bunch of testing on my end, although more testing by other users may be appropriate.

Other mentionable changes:
- Build requirements in README
- Updated VSCode settings
- Some UI cleanup here and there

### CODE REVIEW

**Comment by ACertainCoder** [comment]
Information regarding testing this pull request:

NirSoft's [CurrPorts](http://www.nirsoft.net/utils/cports.html) can be used to close TCP connections manually, imitating a bad Internet connection. A receive timeout can be triggered by disconnecting from the Internet for 10 seconds. In each case, it should try to reconnect __once__ and resume the download. A download is also resumed if the user clicks manually on the retry button.

A completely new download is always triggered if the user clicks on the "install" button. This is to avoid issues where the file might be corrupted and needs to be re-downloaded (could be improved in the future, see #426).

**Review by AlexisL61 — APPROVED** [review]
Looks good to me. I will test tomorrow before merging. Thank you for the great code quality

**Comment by ACertainCoder** [comment]
Thanks for the appreciation. :heart: I also took a last look over the code again and revised to things (use of HttpStatus and renaming the `.part` file instead of copying and deleting it).

**Comment by AlexisL61** [comment]
@all-contributors please add @ACertainCoder for code

**Pull request merged**
